trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: containerregistry12345
  IMAGE_NAME: todo-frontend
  WEBAPP_NAME: web-appname

steps:
- task: Docker@2
  displayName: Build and Push Image
  inputs:
    command: 'buildAndPush'
    repository: '$(IMAGE_NAME)'
    dockerfile: 'Dockerfile'
    containerRegistry: 'docker123'
    tags: |
      latest

- task: AzureWebAppContainer@1
  displayName: Deploy to Web App
  inputs:
    azureSubscription: 'azure resources'
    appName: '$(WEBAPP_NAME)'
    containers: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest'
